name: Test Workflow
on: [pull_request]

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository in ubuntu's file system
        uses: actions/checkout@v1
      - name: Setup JDK 11.0.11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.11
      - name: Print contents in current directory
        run: ls -la
      - name: UI tests
        run: ./gradlew testDebugUnitTest


